apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
  labels:
    app: myproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
        - name: myproject
          image: 205930634535.dkr.ecr.ap-south-1.amazonaws.com/myproject:latest
          ports:
            - containerPort: 8000
